name: CommandTimerTasks
main: ru.leoltron.commandtimertasks.CommandTimerTasks
version: "1.2"

commands:
  CommandTimerTasks:
    description: Basic plugin command
    aliases: [ctt, com]
    usage: /CommandTimerTasks reload